DROP TABLE IF EXISTS "sessions" CASCADE;
DROP TABLE IF EXISTS "users" CASCADE;
DROP TABLE IF EXISTS "role_privileges" CASCADE;
DROP TABLE IF EXISTS "privileges" CASCADE;
DROP TABLE IF EXISTS "roles" CASCADE;